package com.chinaias.webservice.erp;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.1.12
 * 2017-07-24T22:27:17.105+08:00
 * Generated source version: 3.1.12
 * 
 */
@WebServiceClient(name = "CUX_WS_SERVER_FACTORY_PKG_Service", 
                  wsdlLocation = "http://192.168.1.22:9091/webservices/SOAProvider/plsql/cux_ws_server_factory_pkg/?wsdl",
                  targetNamespace = "http://xmlns.oracle.com/apps/cux/soaprovider/plsql/cux_ws_server_factory_pkg/") 
public class CUXWSSERVERFACTORYPKGService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://xmlns.oracle.com/apps/cux/soaprovider/plsql/cux_ws_server_factory_pkg/", "CUX_WS_SERVER_FACTORY_PKG_Service");
    public final static QName CUXWSSERVERFACTORYPKGPort = new QName("http://xmlns.oracle.com/apps/cux/soaprovider/plsql/cux_ws_server_factory_pkg/", "CUX_WS_SERVER_FACTORY_PKG_Port");
    static {
        URL url = null;
        try {
            url = new URL("http://192.168.1.22:9091/webservices/SOAProvider/plsql/cux_ws_server_factory_pkg/?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(CUXWSSERVERFACTORYPKGService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://192.168.1.22:9091/webservices/SOAProvider/plsql/cux_ws_server_factory_pkg/?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public CUXWSSERVERFACTORYPKGService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public CUXWSSERVERFACTORYPKGService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CUXWSSERVERFACTORYPKGService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public CUXWSSERVERFACTORYPKGService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public CUXWSSERVERFACTORYPKGService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public CUXWSSERVERFACTORYPKGService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    




    /**
     *
     * @return
     *     returns CUXWSSERVERFACTORYPKGPortType
     */
    @WebEndpoint(name = "CUX_WS_SERVER_FACTORY_PKG_Port")
    public CUXWSSERVERFACTORYPKGPortType getCUXWSSERVERFACTORYPKGPort() {
        return super.getPort(CUXWSSERVERFACTORYPKGPort, CUXWSSERVERFACTORYPKGPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CUXWSSERVERFACTORYPKGPortType
     */
    @WebEndpoint(name = "CUX_WS_SERVER_FACTORY_PKG_Port")
    public CUXWSSERVERFACTORYPKGPortType getCUXWSSERVERFACTORYPKGPort(WebServiceFeature... features) {
        return super.getPort(CUXWSSERVERFACTORYPKGPort, CUXWSSERVERFACTORYPKGPortType.class, features);
    }

}
