package com.chinaias.webservice.erp;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.1.12
 * 2017-07-24T22:27:17.073+08:00
 * Generated source version: 3.1.12
 * 
 */
@WebService(targetNamespace = "http://xmlns.oracle.com/apps/cux/soaprovider/plsql/cux_ws_server_factory_pkg/", name = "CUX_WS_SERVER_FACTORY_PKG_PortType")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface CUXWSSERVERFACTORYPKGPortType {

    @WebMethod(operationName = "INVOKEFMSWS", action = "http://192.168.1.22:9091/webservices/SOAProvider/plsql/cux_ws_server_factory_pkg/")
    @WebResult(name = "OutputParameters", targetNamespace = "http://xmlns.oracle.com/apps/cux/soaprovider/plsql/cux_ws_server_factory_pkg/invokefmsws/", partName = "body")
    public OutputParameters invokefmsws(
        @WebParam(partName = "header", name = "SOAHeader", targetNamespace = "http://xmlns.oracle.com/apps/cux/soaprovider/plsql/cux_ws_server_factory_pkg/", header = true)
        SOAHeader header,
        @WebParam(partName = "body", name = "InputParameters", targetNamespace = "http://xmlns.oracle.com/apps/cux/soaprovider/plsql/cux_ws_server_factory_pkg/invokefmsws/")
        InputParameters body
    );
}
